apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rag-api
spec:
  selector:
    app: {{ .Release.Name }}-rag-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000