image:
  repository: rag-api
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 8000

env:
  OLLAMA_URL: "http://host.docker.internal:11434"
  EMBED_MODEL: "nomic-embed-text"
  CHAT_MODEL: "llama3.2:3b"
  PGHOST: "postgres"
  PGPORT: "5432"
  PGDATABASE: "ragdb"
  PGUSER: "postgres"

secretName: pg-secret